<?php

return [
	'titleSite' => 'Developers SAC',
	'urlBusiness' => 'https://www.linkedin.com/in/luis-falero-otiniano/',
	'insertMessage' => '!Se ha guardado con exito!',
	'updateMessage' => '!Se ha modificado con exito!',
	'destroyMessage' => '!Se ha eliminado con exito!',	
	'insertErrorMessage' => '!Error al guardar el registro!',
	'updateErrorMessage' => '!Error al modificar el registro!',	
	'destroyErrorMessage' => '!Error al eliminar el registro!',
	'alertTitle' => '¿Realmente desea eliminar el registro?',
	'storePedidoEmisor' => 'Confirmación de registro de solicitud de pedido',
	'storePedidoReceptor' => 'Evaluación de solicitud de pedido',
	'checkPedido' => 'Aprobación de Pedido',
	'cancelPedido' => 'Rechazo de Pedido',
	'despacharPedido' => 'Aviso de pedido listo',
	'entregarPedido' => 'Entrega de Pedido',
	'devolverPedido' => 'Devolución de Pedido',
	'stockPedido' => 'Revisar Stock de Producto',
	'checkMessage' => '!Se ha aprobado el pedido con exito!',	
	'checkErrorMessage' => '!Error al aprobar el pedido!',	
	'cancelMessage' => '!Se ha rechazado el pedido con exito!',	
	'cancelErrorMessage' => '!Error al rechazar el pedido!',	
	'printMessage' => '!Se ha impreso el pedido con exito!',	
	'printErrorMessage' => '!Error al imprimir el pedido!',	
	'despacharMessage' => '!Se ha despachado el pedido con exito!',	
	'despacharErrorMessage' => '!Error al despachar el pedido!',
	'devolverMessage' => '!Se ha devuelto el pedido con exito!',	
	'devolverErrorMessage' => '!Error al devolver el pedido!',
	'entregarMessage' => '!Se ha entregado el pedido con exito!',	
	'entregarErrorMessage' => '!Error al entregar el pedido!',
	'success' => 'success',
	'info' => 'info',
	'warning' => 'warning',
	'danger' => 'danger',
	'botonModificar' => 'Modificar',
	'botonGuardar' => 'Guardar',
	'botonAprobar' => 'Aprobar',
	'botonGuardarSeguir' => 'Guardar y seguir registrando',
	'botonRetroceder' => 'Cancelar',
	'botonEnviar' => 'Enviar',
	'MAIL_FROM_ADDRESS' => 'comunicados.falero@gmail.com',
	'MAIL_CONTACT' => 'noreply.falero@gmail.com',
	'MAIL_CONTACT_DEMO' => 'falero.otiniano.luis@gmail.com'
];

?>